services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - statictwitchapi

  authservice:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "4000:4000"
  
  statictwitchapi:
    build:
      context: ./static-twitch-api
      dockerfile: Dockerfile
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_STREAMER_USERNAME=${TWITCH_STREAMER_USERNAME}
      - PORT=${STATIC_TWITCH_API_PORT}
      - URL=${HOST_URL}
    ports:
      - "3001:3001"
